import createClient from "openapi-fetch";
import type { paths } from "./domain-model/api/apiTypes"; // generated by openapi-typescript

export const client = createClient<paths>({
  baseUrl: "http:localhost:3000/api",
});
